### ISSUE TITLE
Dropbox icon is black instead of white when Papirus Dark Plasma theme is selected

### ISSUE THREAD

**Issue by pioneer** [varlesh/papirus-gtk-icon-theme#2]
I think it would be enough to make Dropbox icon just blue, as usual.
![screenshot6](https://cloud.githubusercontent.com/assets/200538/12913925/3d4390e0-cf2a-11e5-8b21-e59cc8461dc0.png)

**Comment by varlesh** [comment]
This repository for only GTK DE. Please use this https://github.com/varlesh/papirus-pack-kde/issues
